baseURL = 'https://yeoleobun.github.io'
languageCode = "en-us"
theme = "anubis2"
title = "yeoleobun's blog"

[author]
name = "yeoleobun"

[taxonomies]
tag = "tags" # This allows you to use the "tags" in your markdown metadata

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 2

[params]
# Meta description
enableLaTeX = true
disableSummary = true

# readMore = false # true | false; Showing readmore link in the list of posts; default: false
# readNextPosts = 3 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "light" # "auto" | "light" | "dark"; default: "auto"
# colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = false # true | false; Showing table of contents in the post; default: true
math = true # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

# check more social icons at https://github.com/Junyi-99/hugo-theme-anubis2/wiki/Social-Icons

# rssIcon = true # true | false; Showing RSS icon; default: true

# Social icons
[[params.social]]
id = "github"
url = "https://github.com/yeoleobun"

[[params.social]]
id = "zhihu"
url = "https://www.zhihu.com/people/boomdrummer"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)'], ['$', '$']]
