baseURL = 'https://yeoleobun.github.io'
languageCode = "zh-CN"
theme = "paper"
title = "&'static blog"

[params]
# color style
color = 'gray' # linen, wheat, gray, light

# header social icons
github = 'yeoleobun'  # github.com/YOUR_GITHUB_ID

# home page profile
avatar = 'https://gravatar.com/avatar/3e163e825b85be85a7e2abb008061a5da835aaaf61d7f155870a846db74579a6' # gravatar email or image url
name = 'l1zz'
bio = '🤔'

# misc
disableHLJS = true          # disable highlight.js
disablePostNavigation = true # disable post navigation
monoDarkIcon = true          # show monochrome dark mode icon
math = true                  # enable KaTeX math typesetting globally
localKatex = false           # use local KaTeX js/css instead of CDN

# giscus
[params.giscus]
repo = 'yeoleobun/yeoleobun.github.io' # see https://giscus.app for more details
repoId = 'R_kgDOHvKegA'
category = 'General'
categoryId = 'DIC_kwDOHvKegM4CgCXY'
mapping = 'pathname'
reactionsEnabled = 1
theme = 'light'
lang = 'zh-CN'

[[params.author]]
name = "yeoleobun"

# Syntax highligth on code blocks
[markup]
  [markup.highlight]
    style = "tango"
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['$', '$']]
